MainApp/urls.py
from django.urls import path
from . import views

app_name = 'MainApp'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas',views.pizzas,name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('new_review/<int:pizza_id>/',views.new_review,name='new_review'),
]

PizzaReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MainApp.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MainApp/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    header_image = models.ImageField(null=True, blank=True, upload_to='images/')
    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=200)
    def __str__(self):
        return self.topping_name

class Review(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.text[:50]}"

MainApp/forms.py
from django import forms
from .models import *

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']
        label = {'text': ''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

MainApp/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
# Create your views here.

def index(request):
    return render(request, 'MainApp/index.html')

def pizzas(request):
    pie = Pizza.objects.order_by('pizza_name')
    context = {'pie':pie}
    return render(request,'MainApp/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    topping = pizza.topping_set.order_by('topping_name')
    new_reviews = pizza.review_set.order_by('date_added')
    context = {'pizza':pizza,'topping':topping,'new_reviews':new_reviews}
    return render(request,'MainApp/pizza.html',context)

def new_review(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = PizzaForm()
    else:
        form = PizzaForm(data=request.POST)

        if form.is_valid():
            new_review = form.save(commit=False)
            new_review.pizza = pizza
            new_review.save()
            return redirect('MainApp:pizzas')
    context={'form':form,'pizza':pizza}
    return render(request, 'MainApp/new_review.html',context)


    

MainApp/templates/mainapp/base.html
<body> 
<font color="Black" face="Helvetica"> 
<p>
    <a href="{% url 'MainApp:index' %}">Pizza Reviews</a>
    <a href="{% url 'MainApp:pizzas' %}">Pizza List</a>
</p>
</body>

{% block content %}

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %}

{% block content %}
<body> 
<font color="Black" face="Helvetica"> 
<p> Welcome to Pizza Reviews</p>

<div style="background-color: rgb(223, 37, 0) ; padding: 15px; border: 1px solid rgb(255, 170, 0);">
    <div style="background-color: rgb(255, 255, 0) ; padding: 15px; border: 1px solid rgb(245, 255, 157);">
<div> One bite, everybody knows the rules </div>
</body>
{% endblock content %}

MainApp/templates/mainapp/new_review.html
{% extends "MainApp/base.html" %}

{% block content %}

<p> Add a new review for {{pizza}}: </p>

<form action="{% url 'MainApp:new_review' pizza.id %}" method='post'>

    {% csrf_token %}
    {{form.as_p}}
    <button name="Submit">Submit Review</button>

</form>

{% endblock content %}

MainApp/templates/mainapp/pizza.html
{% extends "MainApp/base.html" %}
{% load static %}
{% block content %}

<p> {{ pizza }} </p>

{% for t in topping %}
<li> 
    {{ t }}
</li>
    {% empty %}
<li> No toppings have been added...</li>
    {% endfor %}
<p></p>
<p></p>
{% if pizza.header_image %}
<img src="{{ pizza.header_image }}">
{% endif %}

<p> {{ pizza }} Reviews: </p>
    {% for r in new_reviews %}
<li>
    {{r}}
</li>
{% empty %}
<li> No reviews have been added...</li>
    {% endfor %}

<p><a href="{% url 'MainApp:new_review' pizza.id %}">Add a review!</a></p>

{% endblock content %}

MainApp/templates/mainapp/pizzas.html
{% extends "MainApp/base.html" %}

{% block content %}

<p> Check out our list of incredible pizzas! </p>
<ul>
    {% for p in pie %}
    <li> 
        <a href="{% url 'MainApp:pizza' p.id %}"> {{ p }} </a>
    </li>

    {% empty %}
    <li> No pizzas have been added...</li>
    {% endfor %}
</ul>

{% endblock content %}

MainApp/templates/mainapp/static.html
{% load static %}

<img src="{% static 'MainApp\static\images\Homepage.png' $}" alt="One Bite">